# training_config.yaml

data:
  manifest_path: '/data/condor_shared/users/ssued/RNO_vertex_reconstruction_ml/RNO_machine_learning/manifest_builder/manifests/manifest_3albums_500comp.json' # Path to manifest
  cache_dir: '/scratch/users/ssued/rno_cache_compressed' # Path to scratch cache if you have a faster drive.

training:
  batch_size: 256
  num_epochs: 100000
  learning_rate: 0.001
  weight_decay: 0.0 # Usually 1e-4
  checkpoint_freq: 50

resume: # Checkpointing if you want to resume a run. If not, keep null
  checkpoint_path: 
  wandb_id: 9ndw91no

wandb:
  project: model_RNO4_thesis  # groups all runs of this concept
  enabled: true
  notes: Keep AdamW but try previous model
  tags: # Standard syntax for array in YAML
    - compressed
    - 500_shards
    - 3 albums
    - test