# --- Step 1 Submit File ---

# 0. Environment
environment = "HDF5_USE_FILE_LOCKING=FALSE"

# 1. Executable
executable = /data/condor_shared/users/ssued/RNOG_Image_Builder/venv/bin/python3

# 2. Arguments
arguments = -u $(myscript) --output_file $(output_file) --n_nu $(n_nu)

# 3. Logs
log    = $(logdir)/step1_$(job_id).log
output = $(logdir)/step1_$(job_id).out
error  = $(logdir)/step1_$(job_id).out

# 4. Resources
request_cpus = 1
request_memory = 1500GB
queue